# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
print(np.version.version)
print(np.__version__)
print(np.show_config())

2.1.3
2.1.3
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-__cqtv8c/cp312-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-__cqtv8c/cp312-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Haswell MAX_THREADS=24
    pc file directory: D:/a/numpy/numpy/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-__cqtv8c/cp312-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-__cqtv8c/cp312-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLA

#### 3. Create a null vector of size 10 (★☆☆)

In [5]:
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [9]:
b = np.zeros((10,10))
print("%d bytes" % (b.size * b.itemsize))

800 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [18]:
print(np.info(np.add))


add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [20]:
res  = np.zeros(10)
res[4] = 1
print(res)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [21]:
np.arange(10,50,1)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [23]:
a = np.arange(10)
b = a[::-1]
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [25]:
np.arange(9).reshape(3,3)


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [33]:
a = np.nonzero([1,2,0,0,4,0])
print(a)
print(np.info(np.nonzero))

(array([0, 1, 4]),)
Return the indices of the elements that are non-zero.

Returns a tuple of arrays, one for each dimension of `a`,
containing the indices of the non-zero elements in that
dimension. The values in `a` are always tested and returned in
row-major, C-style order.

To group the indices by element, rather than dimension, use `argwhere`,
which returns a row for each non-zero element.

.. note::

   When called on a zero-d array or scalar, ``nonzero(a)`` is treated
   as ``nonzero(atleast_1d(a))``.

   .. deprecated:: 1.17.0

      Use `atleast_1d` explicitly if this behavior is deliberate.

Parameters
----------
a : array_like
    Input array.

Returns
-------
tuple_of_arrays : tuple
    Indices of elements that are non-zero.

See Also
--------
flatnonzero :
    Return indices that are non-zero in the flattened version of the input
    array.
ndarray.nonzero :
    Equivalent ndarray method.
count_nonzero :
    Counts the number of non-zero elements in the input array.

Notes

#### 11. Create a 3x3 identity matrix (★☆☆)

In [4]:
a = np.identity(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [3]:
a = np.random.rand(3,3,3)
print(a)

[[[0.83858988 0.34407458 0.44780744]
  [0.68027439 0.62383096 0.14398834]
  [0.35036003 0.46886391 0.5553933 ]]

 [[0.85492331 0.73168397 0.27294173]
  [0.93732615 0.78958583 0.32546008]
  [0.63331608 0.25629724 0.97607826]]

 [[0.97580628 0.92238748 0.3476989 ]
  [0.72724633 0.55481932 0.19870233]
  [0.23276281 0.12652933 0.98116591]]]


In [8]:
a = np.random.randint(low = -100,high = 100,size = (10,10))
print(a)
print(a.max())
print(a.min())

[[ -50  -59   19  -39   21   83  -11   12   88  -94]
 [ -35   33  -97  -61 -100   39  -82  -10   41   43]
 [  81  -79   15   22  -77   62  -44  -45  -43  -37]
 [  63   22  -19  -62   97  -27   37   21   57  -98]
 [   9  -81   96   60  -19   37  -83   70  -74  -67]
 [   6 -100   74  -34   36  -69   37  -99  -64   97]
 [ -69  -21   36  -64   41  -45   -4  -70  -86  -86]
 [  88  -62   30  -80  -12  -91  -36  -12   18  -33]
 [ -19   96   59   98  -89  -62  -69  -61  -34   79]
 [  23   11  -53   63   17  -62  -88  -79   90  -89]]
98
-100


In [12]:
a = np.random.random(30)
print(a.mean())

0.5680717083156811


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [13]:
a = np.zeros((10,10), dtype = int)
a[:,0] = 1
a[:,-1] = 1
print(a)

[[1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [20]:
n = int(input())
m = int(input())
a = np.ones((n,m))
a = np.pad(a,pad_width = 1,mode = "constant", constant_values = 0)
print(a)

[[0. 0. 0. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [31]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [3]:
import numpy as np
a = np.ones((5,5))
i = 1
j = 0
num = 1
while i < len(a):
    a[i][j] = num
    i += 1
    j += 1
    num += 1
print(a)

Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 2. 1. 1. 1.]
 [1. 1. 3. 1. 1.]
 [1. 1. 1. 4. 1.]]
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [4]:
a = np.zeros((8,8))
a[0::2,0::2] = 1
a[1::2,1::2] = 1
print(a)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


In [18]:
np.unravel_index(99,(6,7,8))

(np.int64(1), np.int64(5), np.int64(3))

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [23]:
a = np.array([[0,1],[1,0]])
a = np.tile(a,(4,4))
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [30]:
a = np.random.randint(low = 10,size = (5,5))
print(a)
a = (a - np.mean(a))/ np.std(a)
print(a)

[[4 3 6 6 3]
 [0 3 2 9 2]
 [3 4 3 7 4]
 [7 6 3 4 0]
 [9 3 3 8 6]]
[[-0.13267163 -0.54727045  0.69652603  0.69652603 -0.54727045]
 [-1.79106694 -0.54727045 -0.96186928  1.94032252 -0.96186928]
 [-0.54727045 -0.13267163 -0.54727045  1.11112486 -0.13267163]
 [ 1.11112486  0.69652603 -0.54727045 -0.13267163 -1.79106694]
 [ 1.94032252 -0.54727045 -0.54727045  1.52572369  0.69652603]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [33]:
color = np.dtype([("r",np.ubyte),
                  ("g",np.ubyte),
                  ("b",np.ubyte),
                  ("a",np.ubyte)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [37]:
a = np.random.randint(low = 10, size = (5,3))
b = np.random.randint(low = 10, size = (3,2))
print(np.dot(a,b))

[[ 99 147]
 [ 37  72]
 [  8  64]
 [ 25  53]
 [ 55  89]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [44]:
a = np.random.randint(low = -10, high = 20, size = (20,))
mask1 = a > 3
mask2 = a < 8
a = np.where(mask1 & mask2, a, -1 * a)
print(a)

Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)


[-11 -16   7  -8   2  10   5   6   0  -8   5 -10   3   7   7  -8   0  -1
   2   0]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [4]:
print(sum(range(5), -1))
# 2 + 3 + 4 + 5
from numpy import *
print(sum(range(5), -1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [55]:
z = np.arange(4)
print(z**z)
print(2 << z >> 2)
print( z < -z)
print(1j*z)
print(z/1/1)
print(z<z>z)

[ 1  1  4 27]
[0 1 2 4]
[False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j]
[0. 1. 2. 3.]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [56]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


C:\Users\Vo Thai Thanh\AppData\Local\Temp\ipykernel_49848\1422587819.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\Vo Thai Thanh\AppData\Local\Temp\ipykernel_49848\1422587819.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
C:\Users\Vo Thai Thanh\AppData\Local\Temp\ipykernel_49848\1422587819.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

In [6]:
import numpy as np
Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

# More readable but less efficient
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))

[-5. -8.  3.  8. -3.  7. -8.  9. -4. -8.]
[-5. -8.  3.  8. -3.  7. -8.  9. -4. -8.]


#### 30. How to find common values between two arrays? (★☆☆)

In [23]:
arr = np.random.randint(low = -10,high = 10 , size = 17)
arr1 = np.random.randint(low = -10,high = 10 , size = 17)
print(np.intersect1d(arr, arr1))
common = arr[np.isin(arr, arr1)]
print(common)

[-10  -9  -5  -2   0   1   7]
[ -2   0  -2  -9 -10  -9   1 -10  -5   7]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [28]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [30]:
np.sqrt(-1) == np.emath.sqrt(-1)


C:\Users\Vo Thai Thanh\AppData\Local\Temp\ipykernel_52076\4279177385.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


np.False_

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [38]:
today = np.datetime64("today")
yes = today - np.timedelta64(1, "D")
print(yes)
print(today)
print(today + np.timedelta64(1, "D"))

2024-12-18
2024-12-19
2024-12-20


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [44]:
date_of_july_2016 = np.arange('2016-07','2016-08', dtype = 'datetime64[D]')
print(date_of_july_2016)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [46]:
A = np.ones(3)*1
B = np.ones(3)*2
print(A,B)
np.add(A,B,out=B)
print(A,B)
np.divide(A,2,out=A)
print(A,B)
np.negative(A,out=A)
print(A,B)
np.multiply(A,B,out=A)
print(A,B)

[1. 1. 1.] [2. 2. 2.]
[1. 1. 1.] [3. 3. 3.]
[0.5 0.5 0.5] [3. 3. 3.]
[-0.5 -0.5 -0.5] [3. 3. 3.]
[-1.5 -1.5 -1.5] [3. 3. 3.]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [57]:
Z = np.random.uniform(0,10,10)

# way 1
print(Z - Z % 1)
# way 2
print(np.floor(Z))
# way 3
print(Z.astype(np.int32))
# way 4
print(np.trunc(Z))

[0. 8. 6. 6. 6. 1. 6. 9. 2. 9.]
[0. 8. 6. 6. 6. 1. 6. 9. 2. 9.]
[0 8 6 6 6 1 6 9 2 9]
[0. 8. 6. 6. 6. 1. 6. 9. 2. 9.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [65]:
arr = np.zeros((5,5))
arr += np.arange(5)
print(arr)

# without broadcasting
Z = np.tile(np.arange(0, 5), (5,1))
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [67]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(), dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [71]:
a = random.random(10)
print(a)
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)



[0.00340015 0.57849809 0.41741193 0.52372555 0.36599239 0.05448237
 0.77997921 0.50359284 0.36392089 0.44051897]
[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [72]:
a = np.random.random(10)
np.sort(a)

array([0.14867991, 0.36232575, 0.41810496, 0.42714378, 0.47248436,
       0.50250035, 0.53794038, 0.918761  , 0.9472442 , 0.95044852])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [79]:
Z = np.arange(10)
np.add.reduce(Z)

np.int64(45)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [84]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

False
False


#### 43. Make an array immutable (read-only) (★★☆)

In [87]:
Z = np.zeros(10)
Z.flags.writeable = False
print(Z)
Z += 1

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


ValueError: output array is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [88]:
import numpy as np

# Step 1: Generate a random 10x2 matrix
cartesian_coords = np.random.rand(10, 2)  # Random values in the range [0, 1)

# Step 2: Compute polar coordinates
x = cartesian_coords[:, 0]
y = cartesian_coords[:, 1]
r = np.sqrt(x**2 + y**2)
theta = np.arctan2(y, x)  # arctan2 handles the correct quadrant

# Combine r and theta into a polar coordinates matrix
polar_coords = np.column_stack((r, theta))

# Display the result
print("Cartesian Coordinates:")
print(cartesian_coords)
print("\nPolar Coordinates:")
print(polar_coords)


Cartesian Coordinates:
[[0.7861212  0.78235121]
 [0.95434846 0.37599597]
 [0.11439703 0.08279547]
 [0.05091779 0.46071914]
 [0.29686232 0.63688821]
 [0.21294878 0.93262242]
 [0.37723255 0.77159123]
 [0.20451915 0.89920956]
 [0.39582149 0.63877525]
 [0.0812354  0.25409921]]

Polar Coordinates:
[[1.10908068 0.78299457]
 [1.02574556 0.37530757]
 [0.14121534 0.62649191]
 [0.46352427 1.46072495]
 [0.70267619 1.13462334]
 [0.95662519 1.34631145]
 [0.85886985 1.11606642]
 [0.92217456 1.34715757]
 [0.75147088 1.01604847]
 [0.26676881 1.26136596]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [97]:
arr = np.random.rand(10)
arr[Z.argmax()] = 0
print(arr)

[0.         0.26495437 0.00882174 0.53256331 0.60611558 0.35209738
 0.8414665  0.06344998 0.57170929 0.2022293 ]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [101]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [107]:
X = np.random.rand(10)
Y = np.random.rand(10)
cauchy_ma = np.zeros((10,10))
for i in range(len(X)):
    for j in range(len(Y)):
        if X[i] != Y[j]:
            cauchy_ma[i][j] = 1/(X[i] - Y[j])
        else:
            cauchy_ma[i][j] = 0
print(cauchy_ma)

X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

[[ -1.11103211  -1.43935443  -2.48754149  -9.93801652  -1.12853973
   -4.77940935  -3.19871076  -1.53364484  -9.21425747  -2.24771415]
 [-21.61002574   6.2879927    2.21343817   1.32772948 -30.94857487
    1.55145004   1.84787133   4.95668533   1.34181052   2.44562911]
 [ -2.59720908  -5.56419227   8.8470552    2.41305984  -2.69494175
    3.2700638    4.94048317  -7.2989429    2.45997715  14.25742833]
 [ -2.51897916  -5.21707919   9.89369885   2.48475555  -2.61080885
    3.40313269   5.25067168  -6.71304624   2.534531    17.18763894]
 [ -3.81993181 -17.70641794   4.2323408    1.85992699  -4.03516035
    2.33073971   3.07075077 -72.66262656   1.88767664   5.17109113]
 [ -1.64005547  -2.47263171  -8.95456938   5.27134748  -1.67849355
   12.33081487 -44.84820339  -2.76462331   5.50051824  -6.46964805]
 [ -3.18271128  -9.18362686   5.43882849   2.06082412  -3.33073125
    2.65508628   3.65977936 -15.11145204   2.09494718   7.09370589]
 [ -1.11173111  -1.44052781  -2.49104821  -9.99422435  

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [108]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [109]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [117]:
Z = np.arange(100)
v = np.random.uniform(0,100)
print(v)
index = (np.abs(Z-v)).argmin()
print(Z[index])

88.97853890486377
89


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [120]:
import numpy as np

Z = np.zeros(10, dtype=[('position', [('x', float), ('y', float)]),
                       ('color', [('r', float), ('g', float), ('b', float)])])

# Access the 'position' field for all elements
print(Z['position'])

# Access the 'x' values within the 'position' field for all elements
print(Z['position']['x'])

# Access the 'y' values within the 'position' field for all elements
print(Z['position']['y'])

# Access the 'position' for the first element
print(Z[0]['position'])

# Access the 'x' value for the first element
print(Z[0]['position']['x'])

# Access the 'y' value for the first element
print(Z[0]['position']['y'])


[(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
 (0., 0.) (0., 0.)]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
(0.0, 0.0)
0.0
0.0


|#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [129]:
Z = np.random.randint(-10,10,(10,2))
print(Z)
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
print(X)
print(X.T)
print(Y)
print(Y.T)
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)


import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[ 3 -5]
 [-5  9]
 [ 6  7]
 [-5 -6]
 [-8 -6]
 [ 9  9]
 [-8  8]
 [ 8  1]
 [ 3  9]
 [ 9 -6]]
[[ 3 -5  6 -5 -8  9 -8  8  3  9]]
[[ 3]
 [-5]
 [ 6]
 [-5]
 [-8]
 [ 9]
 [-8]
 [ 8]
 [ 3]
 [ 9]]
[[-5  9  7 -6 -6  9  8  1  9 -6]]
[[-5]
 [ 9]
 [ 7]
 [-6]
 [-6]
 [ 9]
 [ 8]
 [ 1]
 [ 9]
 [-6]]
[[ 0.         16.1245155  12.36931688  8.06225775 11.04536102 15.23154621
  17.02938637  7.81024968 14.          6.08276253]
 [16.1245155   0.         11.18033989 15.         15.29705854 14.
   3.16227766 15.26433752  8.         20.51828453]
 [12.36931688 11.18033989  0.         17.02938637 19.10497317  3.60555128
  14.03566885  6.32455532  3.60555128 13.34166406]
 [ 8.06225775 15.         17.02938637  0.          3.         20.51828453
  14.31782106 14.76482306 17.         14.        ]
 [11.04536102 15.29705854 19.10497317  3.          0.         22.6715681
  14.         17.4642492  18.60107524 17.        ]
 [15.23154621 14.          3.60555128 20.51828453 22.6715681   0.
  17.02938637  8.06225775  6.        

ModuleNotFoundError: No module named 'scipy'

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [131]:
Z = (np.random.rand(10)*100).astype(np.float32)
print(Z)
Y = Z.view(np.int32)
print(Y)
Y[:] = Z
print(Y)

[53.958206  34.834583   3.048358   3.8308685 27.960629  68.69409
 50.488567  33.684696  76.676544  58.69667  ]
[1113052468 1108039325 1078138956 1081421043 1105178462 1116300128
 1112142923 1107737889 1117346404 1114294628]
[53 34  3  3 27 68 50 33 76 58]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [133]:
from io import StringIO

# Fake file
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int32)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [134]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)